print('Hi, there! I have an exciting story to tell about my trip to the amusement park!')
print('Before I begin I have a few questions')
print('After typing your answer, please press enter key.')
input(f'\nPress enter to continue')

print('Hi I am Timmy I will be exploring an amusement park')
print('The park is called Universal Studios')
input(f'\nWow! I bet you are excited!')
print('yes I am!')
input(f'\nI can only imagine!')
print('What will you be doing here?')
print('I will be recording while on park rides')
print('Are you excited?')
answer_1 = input('yes or no')
print('what is the situation?')
print('I cant ride because I am too short')
print('Are you at least 48 inches tall?')
answer_1 = input('yes or no')
print('No')
print('Should I stay to play games?')
answer_1 = input('yes or no')
print('yes')
print('Ok great!')

